version: '3.8'

services:
  audio-streamer:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: aposazhennikov/audio-streamer:latest
    container_name: audio-streamer
    privileged: true
    ports:
      - "8000:8000"
    volumes:
      - /home/politics:/app/politics
      - /home/humor:/app/humor
      - /home/science:/app/science
      - /home/nature:/app/nature
      - /home/shaov:/app/shaov
      - /home/troshin:/app/troshin
      - /home/test_audio:/app/test_audio
    environment:
      - STREAM_FORMAT=mp3
      - BITRATE=128
      - MAX_CLIENTS=500
      - LOG_LEVEL=info
      - BUFFER_SIZE=65536
      - DIRECTORY_ROUTES={"humor":"/app/humor","science":"/app/science"}
      - SHUFFLE=false
      - ROUTES_SHUFFLE={"humor":"true","science":"false"}
      - NORMALIZE_VOLUME=true
      - NORMALIZE_RUNTIME=auto
      - NORMALIZE_SAMPLE_WINDOWS=6
      - NORMALIZE_SAMPLE_MS=200
      - STATUS_PASSWORD=1234554321
      - SENTRY_DSN=https://f5dbf565496b75215d81c2286cf0dc9c@o4508953992101888.ingest.de.sentry.io/4509243323908176
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    restart: unless-stopped 