services:
  audio-streamer:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: aposazhennikov/audio-streamer:latest
    container_name: audio-streamer
    privileged: true
    ports:
      - "8000:8000"
    volumes:
      #- /home/politics:/app/politics
      - /home/humor:/app/humor
      - /home/science:/app/science
      - /home/floyd/:/app/floyd/
      #- /home/nature:/app/nature
      - /home/shaov:/app/shaov
      #- /home/troshin:/app/troshin
      #- /home/test_audio:/app/test_audio
      - ./relay_data:/app/relay_data:rw
    environment:
      - BITRATE=128
      - MAX_CLIENTS=10
      - LOG_LEVEL=error
      #- DIRECTORY_ROUTES={"test_audio":"/app/test_audio","humor":"/app/humor","science":"/app/science","politics":"/app/politics","nature":"/app/nature", "shaov":"/app/shaov", "troshin":"/app/troshin"}
      - DIRECTORY_ROUTES={"floyd":"/app/floyd/","humor":"/app/humor","science":"/app/science","shaov":"/app/shaov"}

      - SHUFFLE=false
      # - ROUTES_SHUFFLE={"humor":"true","science":"false"}
      - NORMALIZE_VOLUME=false
      - NORMALIZE_RUNTIME=off
      - NORMALIZE_SAMPLE_WINDOWS=0
      - NORMALIZE_SAMPLE_MS=0
      - STATUS_PASSWORD=1234554321
      - SENTRY_DSN=https://f5dbf565496b75215d81c2286cf0dc9c@o4508953992101888.ingest.de.sentry.io/4509243323908176
      # Relay configuration
      - RELAY=true
      - RELAY_CONFIG_FILE=/app/relay_data/relay_list.json
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    restart: unless-stopped 